name: Continous-Integration
on: [push]
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  XCODEBUILD_DERIVED_DATA_PATH: ".build"
  XCODEBUILD_IPHONESIMULATOR_VERSION: $(xcodebuild -showsdks | grep -e "iphonesimulator" | sort | tail -n 1 | awk '{ print $4}')
  XCODEBUILD_DESTINATIONS: ""
  XCODEBUILD_WORKSPACE: "Experiment.xcworkspace"


jobs:
  prepare:
    name: Prepare tooling
    runs-on: macos-latest
    steps:
      - name: Select Xcode Version
        run: |
          sudo xcode-select -switch /Applications/Xcode_11.2.1.app
  build:
    name: Build
    needs: prepare
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies
      - name: Build application
        run: |
          xcodebuild build-for-testing -scheme Experiment -workspace $XCODEBUILD_WORKSPACE -sdk iphonesimulator -derivedDataPath $XCODEBUILD_DERIVED_DATA_PATH
